### ISSUE TITLE
Extraire les données critiques de l'index Git

### ISSUE THREAD

**Issue by techerjeansebastienpro** [AymericAF/Projet-4-Creer-un-blog-pour-ecrivain#1]
https://github.com/AymericAF/Projet-4-Creer-un-blog-pour-ecrivain/blob/19ca24398eb6d9d417ffaed86e94b2336f398a2b/model/ConnexionManager.php#L9

Tu peux mettre toute les config critiques dans un fichier ignoré par GIT
step 1 
- parameters.php à la racine         | avec les vrai config dedans 
- parameters.dist.php à la racine  | avec juste les clés de la config et des chaines vides +  commentaires
step 2
dans .gitignore, tu ajoute parameters.php

**Comment by AymericAF** [comment]
Done.
